"""Central prompt library for FluidRAG."""

from .header_detection import HEADER_DETECTION_SYSTEM
from .passes import (
    PASS_PROMPTS,
    MECHANICAL_PROMPT,
    ELECTRICAL_PROMPT,
    CONTROLS_PROMPT,
    SOFTWARE_PROMPT,
    PROJECT_MANAGEMENT_PROMPT,
)

__all__ = [
    "HEADER_DETECTION_SYSTEM",
    "PASS_PROMPTS",
    "MECHANICAL_PROMPT",
    "ELECTRICAL_PROMPT",
    "CONTROLS_PROMPT",
    "SOFTWARE_PROMPT",
    "PROJECT_MANAGEMENT_PROMPT",
]
